# Generated by Django 4.2.4 on 2023-08-24 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField()),
                ('minutes', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('offensive_rebounds', models.PositiveIntegerField()),
                ('defensive_rebounds', models.PositiveIntegerField()),
                ('steals', models.PositiveIntegerField()),
                ('blocks', models.PositiveIntegerField()),
                ('turnovers', models.PositiveIntegerField()),
                ('defensive_fouls', models.PositiveIntegerField()),
                ('offensive_fouls', models.PositiveIntegerField()),
                ('free_throws_made', models.PositiveIntegerField()),
                ('free_throws_attempted', models.PositiveIntegerField()),
                ('two_pointers_made', models.PositiveIntegerField()),
                ('two_pointers_attempted', models.PositiveIntegerField()),
                ('three_pointers_made', models.PositiveIntegerField()),
                ('three_pointers_attempted', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_make', models.BooleanField()),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('player_statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='app.playerstats')),
            ],
        ),
        migrations.AddField(
            model_name='playerstats',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='app.team'),
        ),
    ]
